### ISSUE TITLE
Quantity of a product cannot be modified when you try to make a return

### ISSUE THREAD

**Issue by FranRomero** [Oksydan/falcon#366]
### Description

If you try to make a return of an order, you cannot select the quantity of product you want to return. Instead, when you click on quantity select, it checks/uncheck the row of the product in which you click on.

### Node.js version

v18.17.0

### php version

v8.1

### OS and it's version

MacOs Ventura 13.6.1

### Required module/theme

theme

### Reproduction steps

```bash
Prestashop Version: v.8.0.4

1. BO: You have to activate returns. You can do it on "Customer Service > Merchandise Returns" and click on "Enable returns" button.
2. FO: you have to make an order with more than 1 product (f.ex 3 items of a product)
3. BO: Change the state of the order to "Delivered".
4. FO: Log in with the same customer that you have placed the order and go to details of the order that you have placed before. Try to make a return. A modal will appear and you will see that you cannot modify the quantity of products that you want to return because when you click on quantity select, the checkbox of the row just check/uncheck when you click on the full row, but the quantity select, cannot be modified.

PS: Understand BO as Back Office and FO as Front Office

I have tried to make a return on a clean PS v.8.0.4 and modal does not appear so I guess it is something related about this theme.

Thank you!
```

**Comment by FranRomero** [comment]
I have confirmed that is something related with falcon theme and the way it is handling each product row. I guess it is blocking default behaviour with Javascript when any click on a row is executed. I have made a video in which you can see the wrong behaviour. It should allow modify the quantity of product to return.

https://github.com/Oksydan/falcon/assets/8860880/ad345569-8b81-460d-8a5f-ece127d65d90

**Comment by Oksydan** [comment]
HI @FranRomero,

I was able to reproduce the problem.
I am adding this to Falcon 4 road map.
Thank you for your contribution.

**Comment by maofree** [comment]
Hi
the problem is into templates/customer/_partials/order-details-return-table.tpl
find this code
$product.product.is_virtual

replace it with

$product.is_virtual

bye

**Comment by maofree** [comment]
I checked better and in that popup there are more errors, in the meantime I found this.
I'm also interested in solving it for the current version of falcon

**Comment by FranRomero** [comment]
Thank you @maofree, with your fix the problem that I described above is solved.

But doing some test, I have seen that there is another bug related with this screen @Oksydan. If you select one row clicking on the product row checkbox, it is marked correctly, but if you click on "Select all" checkbox and then try to mark any of the product rows checkbox, you are not able to select them.

Should I create a new ticket or does this ticket can be used for both as they are totally related?

Thanks!

**Comment by maofree** [comment]
Hi
yes you are right, there is also a problem on that checkbox to select all items
I think it is present also in the classic theme
I've done several tests but I still can't find the error, it should be a problem in javascript

**Comment by Oksydan** [comment]
Hi @maofree,

if you would like to fix it for version 3.X. You can submit PR.
Make sure that you create a branch from 3.X.X branch and make sure to target this branch for you PR.
Current develop branch contains multiple changes for version 4.0.0.
